repo:
  - ./*
  
# Add '@domain/core' label to any change within the 'core' package
backend:
  - backend/*
  - hackathon/*
  - account/*

frontend:
  - src/*
  - public/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
  - test.py
