# Generated by Django 3.0 on 2019-12-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_hackathonevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTeamProgress',
            fields=[
                ('team_name', models.TextField(primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('team_number', models.IntegerField(null=True, unique=True)),
                ('is_kit_received', models.BooleanField(default=False)),
                ('problem_statement_select_time', models.DateTimeField(null=True)),
                ('project_name', models.TextField(null=True)),
                ('is_repo_private', models.BooleanField()),
                ('tech_stack', models.TextField()),
                ('first_midnight_snack_status', models.BooleanField()),
                ('first_breakfast_status', models.BooleanField()),
                ('first_lunch_status', models.BooleanField()),
                ('first_dinner_status', models.BooleanField()),
                ('second_midnidht_snack_status', models.BooleanField()),
                ('second_breakfast_status', models.BooleanField()),
                ('second_lunch_status', models.BooleanField()),
                ('second_dinner_status', models.BooleanField()),
                ('drinks_count', models.IntegerField()),
                ('day_one_evaluation_one', models.FloatField()),
                ('day_one_evaluation_two', models.FloatField()),
                ('day_two_evaluation_one', models.FloatField()),
                ('day_two_evaluation_two', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('problem_statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.ProblemStatement')),
            ],
        ),
    ]
