# Generated by Django 3.0 on 2019-12-07 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_hackathonevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='domain',
            field=models.ManyToManyField(to='hackathon.ProblemDomain'),
        ),
    ]
